### ISSUE TITLE
笔记中的标题需不需要修改格式

### ISSUE THREAD

**Issue by dengsibao** [yinote/pc#18]
![image](https://f.cloud.github.com/assets/6688116/2479655/9c6cea32-b09e-11e3-873f-9fe75dba5170.png)

**Comment by yb7** [comment]
不需要------------------ 原始邮件 ------------------
发件人: "浮生"notifications@github.com
发送时间: 2014年3月21日(星期五) 上午10:16
收件人: "yinote/pc"pc@noreply.github.com;
主题: [pc] 笔记中的标题需不需要修改格式 (#18)

&mdash;
