### ISSUE TITLE
编辑完待办事项，点击保存时，超过字数限制提醒

### ISSUE THREAD

**Issue by lmykjj** [yinote/pc#71]
正常情况下，应该是点击保存一次或者多次时，字数限制提醒都只出现一次，
![qq 20140909134123](https://cloud.githubusercontent.com/assets/8372948/4197167/725d975a-37e4-11e4-9ed4-03857d4c6788.jpg)

**Comment by wangyazhen** [comment]
最好加上描述正常情况下是什么样子的  过一段时间可能会忘掉

**Comment by lmykjj** [comment]
已解决
